#!/bin/bash

data=$(date "+%F")
data_day=${data: -2}

cd $HOME

flag=0

exist=$(find -name "Backup-*" -type d | wc -l)

if [[ $exist -eq 0 ]]; then
  mkdir "Backup-$data"
  echo -e "Backup folder created !"
  flag=1
fi

if [[ $flag -eq 0 ]]; then
  for backup in *; do
    if [[ $backup == "Backup-"* ]]; then
      backup_day=${backup: -2}
      difference=$((data_day - backup_day))
      if (( "$difference" > 7 )); then
        mkdir "Backup-$data"
        echo -e "Backup folder created !"
        flag=1
        break   
      fi
    fi 
  done
fi

if [[ $flag -eq 0 ]]; then
  echo -e "\n==========INFO==================\n\n" >> "$HOME/backup-report" 
  echo -e "FILE NAME: Backup-$data\nDATA: $data\n" >> "$HOME/backup-report"
  for file in $(find "$HOME/source/"); do
    filename=${file##*/} 
    cd "$HOME/Backup-$data"
    existfile=$(find -name "$filename" -type f | wc -l)
    if [[ -z "$filename" ]]; then 
      continue  
    fi
    if [[ $existfile -eq 0 ]]; then
      cp "$HOME/source/$filename" "$HOME/Backup-$data"
       echo -e "FILE: $filename added to $HOME/Backup-$data" >> "$HOME/backup-report"
       echo -e "FILE: $filename added to $HOME/Backup-$data"
    fi
 
    filesize=$(stat -c%s "$HOME/source/$filename")
    for filecomp in $(find "$HOME/Backup-$data/"); do
      filecompname=${filecomp##*/}
      if [[ -z "$filecompname" ]]; then
        continue
      fi
      filecompsize=$(stat -c%s "$HOME/Backup-$data/$filecompname")
      if [[ "$filename" == "$filecompname" ]]; then
        if [[ "$filesize" == "$filecompsize" ]]; then
          continue
        else
          mkdir "$HOME/tmp"
          cp "$HOME/source/$filename" "$HOME/tmp/$filecompname"
          mv "$HOME/tmp/$filecompname" "$HOME/Backup-$data/$filecompname.$data" 
          rm -rf "$HOME/tmp"
      
          echo -e "$filecompname.$data was created" >> "$HOME/backup-report"
          echo -e "file: $filecompname.$data added to $HOME/Backup-$data\n"
        fi
      fi
    done
  done
  echo -e "\n================================\n\n" >> "$HOME/backup-report"
else
  cd "$HOME/source"
  cp * "$HOME/Backup-$data"  
  echo -e "\n================INFO===================\n\n" >> "$HOME/backup-report"
  echo -e "FILE NAME: Backup-$data\nDATA: $data\n" >> "$HOME/backup-report"
  for each in *; do
    echo -e "$each - copyed" >> "$HOME/backup-report"
  done
  echo -e "\n=======================================" >> "$HOME/backup-report"
fi


